### PR TITLE
* Fixed bug with flora spawn duplication

### LINKED ISSUE #236: Double spawn of resources
image

It might be related to fish overspawning. I think everything is spawned two times. It's not related to the number of players. I'll try to find more information debugging.

### PR DESCRIPTION
**Pull request by killzoms**
Fixes #236

Reorganized method keeping end result whilst filtering and removing duplicated materials.

### CODE REVIEW

**Comment by killzoms** [comment]
just occurred to me that i forgot to add a filter for nickel sulfur and kyanite... diamonds that spawn naturally on the seabed will also need to be fixed... will do when i wake up.

**Comment by quimnuss** [comment]
Then I guess Magnetite as well?

**Comment by Sunrunner37** [comment]
I'm not sure that this is the correct fix for the problem.  This code path is invoked when the server tells the client to spawn entities.  Filtering out entities, and allowing the clients original entities to remain, will cause the server and client guids to become out of sync.  Generally this might be OK for flora (as guids are mostly static); however, we want the server to always be authoritative on the guids.  I think we may want to dig deeper and figure out why the client is spawning flora, disable that code path, and allow the server entities to spawn as they would normally.

**Comment by killzoms** [comment]
From what I can tell 
```c#
ParseFile(batchId, "", "other", spawnPoints);
```
is the origin of the spawning for flora however i am uncertain as to how many other things are spawned by it.

**Comment by Sunrunner37** [comment]
That is the origin of the spawning on the server side which should remain as-is because it is authoritative.  We need to find the source of the client side spawning (somewhere in assembly-csharp) and patch it to disable.

**Comment by killzoms** [comment]
I believe this will work.

**Comment by MarijnS95** [comment]
There was a recent PR (https://github.com/SubnauticaNitrox/Nitrox/pull/212) that used Persistent patches for a similar reason; as you can see it requires an extra check to not change behaviour in the single player environment.

I didn't get to reply to it, but I'd much rather prefer fixing **Non**Persistent patches to run before **anything** we possibly want to do, instead of having a few of these inbetween _semi-persistent_ patches.

**Comment by killzoms** [comment]
Thank you for referencing that PR it was very informative! I wish to dig deeper however I have hit a bit of a snag. One of the methods I am trying to patch makes use of ``this`` key words and I do not know how to access ``this`` key words from the patch. I have attempted to patch manually via dnSpy to no avail...
The class and method that I think is the origin is ``LargeWorldEntity`` which is also a type and ``Start`` I have been trying to patch in a simple ``UnityEngine.MonoBehaviour.print()`` which logs information to output_log

**Comment by MarijnS95** [comment]
@killzoms It is possible to use an argument named `__instance` in the Prefix/Postfix method, Harmony will fill that with a reference to `this`. There are more such substitutions: check the Harmony wiki/documentation and/or other patches.

Good luck finding the source :wink:

**Comment by AlexejheroYTB** [comment]
Fixes #236

**Comment by MarijnS95** [comment]
@AlexejheroYTB It has to be in the PR description for that to work; see how it has an underline and informative tooltip?

**Comment by AlexejheroYTB** [comment]
Yep. Thanks for the info!

**Comment by Sunrunner37** [comment]
Let us know when this is ready for review again.

**Comment by killzoms** [comment]
Running tests on PaxTerrainController.LoadAsync() method.

**Comment by Sunrunner37** [comment]
Do you need to change that exact line or can you patch the code inside that function?

**Comment by killzoms** [comment]
either or should do however i have no skill whatsoever with dealing with Transpilers...

**Comment by killzoms** [comment]
Noticed that calling Multiplayer.Main.IsMultiplayer() before loading multiplayer returns null

**Comment by Sunrunner37** [comment]
Thanks for compiling the full list!

**Pull request merged**
