### PR TITLE
Fixed building all kinds of tubes

### PR DESCRIPTION
**Pull request by CtrlAltDavid01**
This SEEMS to fix the building problem, let me know if I broke something.

- The tubes are now building properly
- Deconstruction is not fixed
- When deconstructing other things can deisappear too

I'll try to fix deconstruction too
(I tested it with multiple clients)

### CODE REVIEW

**Comment by acidscorch** [comment]
The problem is more complex:
- duplicated or overlapping items in save file (with same positions, so the multilplayer builder can't place them which causes guid messed up)
- base_geometry patch reaplies guids from deconstructed objects (which also causes guid messed up)
- begin deconstructing hook doesn't transfer guids in all cases to deconstructable
- bases spawn when deconstructing a middle Element of long reaching corridors which needs reassing of new Base guid to objects
- deconstructed objects are not correctly removed from build History
- Initialplayer sync is Not ordered so attached objects (like solarpanel are placed before the grounding Base piece)

**Comment by CtrlAltDavid01** [comment]
I noticed it while trying to debug the thing, but this fixed the building part, I reloaded the server multiple times, I had 2 clients online and while I didn't deconstruct anything it worked.
I hope I'll understand the problem.

**Comment by acidscorch** [comment]
I've already quite a lot of tracing output in my test-code. I will test your change the next days and have a look, if it also works with more complex use cases.

**Comment by acidscorch** [comment]
Hmm... at first review, i can't see a difference to the original patch for the constructor. The Method "MakeCellDeconstructable" is called directly after the "Constructor". 
Have a look at my log and search for "BaseDeconstructable_Post_Constructor" (there may be 2 or 3 lines for this method call, if a guid needs to be updated) and directly after that the "MakeCellDeconstructable" is called. 
https://www.dropbox.com/s/d8kck16kax5yshe/nitrox-2019-04-07.log?dl=0

Maybe i'm missing something, but for me it seems that both ways lead to the same endresult after calling.

**Comment by CtrlAltDavid01** [comment]
Okay, I'll have a look, I thoughtthe same thing, but no matter how many times I tested, the corridors finnishd building correctly with this patch and without it it broke instantly.
Maybe I just didn't find the real reason for the problem.

**Comment by CtrlAltDavid01** [comment]
I know what Idid differently, I  store the transfor gameobject, not the BaseDeconstructable.
And I  forgot to rename the .cs file.

**Comment by acidscorch** [comment]
Hmm, sounds interesting. Besides the log shows the same guids for BaseDeconstructable.GameObject and Geometry.GameObject, so i think they are the same. Okay, i will make more and deeper tests tomorrow.

**Comment by NitroxPower** [comment]
Here i had reported all the building issues i had found so far if you want you can take a look #691

**Comment by CtrlAltDavid01** [comment]
It seemed to fix the reinforments and the windowsthatcan be added, but not 100% sure about that

**Comment by acidscorch** [comment]
Hi, i've tried different variants and also broken save games. 
You are right that "MakeCellDeconstructable" is not called for all interiour base pieces that are connected to a base piece (windows, reinforcements, ladders, reactors, watermachine, modulstation, watertank and so on).
So the guid transfer for outer objects is no more interfered by this method.
I need to check now deeper how to make the guid transfer for these objects or if we even need the transfer here. Maybe they can be handled like normal constructables.

**Comment by acidscorch** [comment]
I think that this change can be pulled. For now it skips the problematic objects and skips also the problem, that e.g. ladders or tanks generate two basedeconstructables instead of one. Maybe we have to change back later to constructor, when the other objects are correct handled.
But for now it's a little improvement to the current state and shouldn't brake something.

**Comment by CtrlAltDavid01** [comment]
I'll rename the file correctly  and then it canbe pulled

**Comment by acidscorch** [comment]
Hello CtrlAltDavid01,

could you have a look at Issue#691 and maybe test the solution?

**Comment by CtrlAltDavid01** [comment]
Okay, It fixed point 1,2. Posters place, but they are falling infinitely.

**Comment by Sunrunner37** [comment]
Closing this out as there has been a lot of separate movement on this issue in https://github.com/SubnauticaNitrox/Nitrox/issues/951

**Pull request closed without merging**
