### PR TITLE
This is a gift to you

### PR DESCRIPTION
**Pull request by killzoms**
ClassId: 8d3d3c8b-9290-444a-9fea-8e5493ecd6fe is Reaper Leviathan

### CODE REVIEW

**Comment by NitroxPower** [comment]
Does this fix anything that you changed what does it do?

**Comment by killzoms** [comment]
doesnt fix anything but it does slightly change whats done on a specific date. though this likely shouldnt have been done in this spot but a different one

**Comment by JustinHoeky** [comment]
If i'm correct, it will spawn a Reaper Leviathan in front of the player on 1th of April.
I would love to see their faces, but not sure if the admins will allow it haha

**Comment by killzoms** [comment]
@JustinHoeky You see why its a gift?

**Comment by Sunrunner37** [comment]
Best PR thus far.

**Comment by Dessix** [comment]
@JustinHoeky It appears every single entity that would be spawned on that day would be a reaper leviathan. I don't think even the player would spawn at that point...

**Pull request closed without merging**
