### PR TITLE
Upgraded Litenetlib to 1.2.0

### PR DESCRIPTION
**Pull request by dartasen**
peer is now deriving from IPEndpoint

https://github.com/RevenantX/LiteNetLib/releases/tag/v1.2.0

### CODE REVIEW

**Review by Coding-Hen — APPROVED** [review]

**Review by Jannify — APPROVED** [review]
LGTM CW

**Comment by tornac1234** [comment]
HATTPRIG ?

**Review by Measurity — APPROVED** [review]
LGTM GACW

**Comment by dartasen** [comment]
IDUWYAS

**Comment by Measurity** [comment]
AWSTTCLGIGAACW

**Pull request merged**
