### PR TITLE
Add Swedish language

### PR DESCRIPTION
**Pull request by mattiasghodsian**
There my contribution for Swedish language

### CODE REVIEW

**Comment by dartasen** [comment]
Thank's for your contribution 😄
I'm closing this one since we recently switched to a translation platform, will port this soon, unless you wanna do it.

**Comment by mattiasghodsian** [comment]
> Thank's for your contribution smile I'm closing this one since we recently switched to a translation platform, will port this soon, unless you wanna do it.

I made a request for a new translation

**Comment by Jannify** [comment]
> > Thank's for your contribution smile I'm closing this one since we recently switched to a translation platform, will port this soon, unless you wanna do it.
> 
> I made a request for a new translation

I accepted the request 👍

**Comment by mattiasghodsian** [comment]
all done

**Pull request closed without merging**
