### PR TITLE
Changing position of Status Bars in-game

### PR DESCRIPTION
**Pull request by kylinator25**
*Hopefully* these changes will work and each player's status bar will appear next to their ping in the Ping Manager in the PDA instead of taking up half of the valuable screen space we have.

### CODE REVIEW

**Comment by Oceride** [comment]
What is the discord because i have a dedicated server that you can test on if you want.

**Comment by Sunrunner37** [comment]
Thanks for the contribution.  Just a few tips to help you along:

1) Please make sure that your feature is well-tested, stable, and working.  Although the master branch has some bugs, we don't want to knowingly commit outstanding bugs.  Before filing a PR, I recommend checking out into a new workspace (so you can see what it is like for someone else), recompile, and test.

2) In general, we don't normally commit commented code as these can easily be seen in version control.  If you intend to deprecate a piece of functionality, feel free to remove all aspects of it to keep the code clean.

3) If you are changing something graphical it is best to upload a screenshot so we can see what the user experience is.  This will help us guide our feedback.

With that being said, I pulled these changes locally and I'm wasn't able to see anything.  Can you note the above items, validate locally, and check back in?

**Comment by kylinator25** [comment]
Yeah I realised after this that the reason my tests weren't actually doing anything is that the in-game status bars are actually disabled, and I have no idea how to re-enable them because I don't actually know how they were disabled, so it would probably be a good idea to close this PR and figure out something else

**Comment by MarijnS95** [comment]
You don't need to abandon this PR, you can always close it and reopen at some point in the future. That is, assuming you know how to rebase this branch or otherwise get it up to date and forcepush it with the new changes. Guessing from the branchname, I assume you're uploading changes through the GitHub web interface, that makes things significantly more complicated. You can always contact me here or on Discord and I'll be more than glad to assist on anything `git` related.

Also, as kind of a personal request: You have a few stale (outdated, unused) branches lying around. Would you mind updating those, moving the changes to a recent branch or remove them entirely? As for the ones you intend to use, consider renaming them; that way everyone browsing the tree knows what you are working on or have been working on. :+!:

**Comment by kylinator25** [comment]
Thanks, I'll close it and reopen it. As for the outdated branches, you think you could PM me about that? My name on Discord is the same here, Kylinator25.

**Pull request closed without merging**
