### PR TITLE
Improve: added new launcher design

### PR DESCRIPTION
**Pull request by keyboardfox**
Improved the current launcher with an updated and cleaner UI 
[Design files on Figma](https://www.figma.com/file/DMdu6DJz8Jyh6uykFZaAlfmX/)

### CODE REVIEW

**Comment by dartasen** [comment]
Can be great, would you mind giving us some screenshots please ?

**Comment by keyboardfox** [comment]
Hey @dartasen! Thanks :) I am the designer of the original launcher and wanted to try to implement the design improvements I have made over the last weeks. Here are some screenshots of the new design working. 

LauncherHome
ServerTab
ServerTabConsole
OptionsTab

**Comment by dartasen** [comment]
@keyboardfox I'm a flat UI design lover so I really like those improvements but there are a few details that I think can be improved:

- The homepage is too compact, informations are grouped in a small rectangle, it disturbs me a little
- Overall, I find the new design quite dark, on the current design images remedy this by adding color and immersion in the game that is missing a bit in this version

**Comment by keyboardfox** [comment]
@dartasen That's great feedback, thank you! 

> "The homepage is too compact, informations are grouped in a small rectangle, it disturbs me a little"
I agree with you there, my main goal was to have a scrollview and have the information also spread out fruther apart. I did not want to resize the launcher yet, but ideally it should be a bit wider. Maybe you have some ideas how to achieve the scroll? You can also take a look at the figma design files, it explains the idea a bit better perhaps

> "Overall, I find the new design quite dark, on the current design images remedy this by adding color and immersion in the game that is missing a bit in this version"
Here it's mainly the image causing this, it's currently not the final picture and we had a plan to add some that contain other players to give a better expectation of the mod! I think that once we have some better images that should definetly help a lot. Also the text readability is much better like this :) I based the colours of the dark theme from the website https://nitrox.rux.gg/

**Pull request merged**
