### PR TITLE
Adding ServerJsonSerializer to save world/player/base data as json

### PR DESCRIPTION
**Pull request by Jannify**
For testing change the `serverserializermode` in `NitroxModel.Server.ServerConfig` to `ServerSerializerMode.JSON`

### CODE REVIEW

**Comment by Sunrunner37** [comment]
This is still marked as draft, let me know when you want a review.

**Comment by Jannify** [comment]
For testing change the `serverserializermode` in `NitroxModel.Server.ServerConfig` to `ServerSerializerMode.JSON`

**Comment by Jannify** [comment]
Waiting for #1098

**Comment by Jannify** [comment]
For viewing the huge json files I recommend https://www.mitec.cz/jsonv.html

**Pull request merged**
