### PR TITLE
Initial contributing guideline.

### PR DESCRIPTION
**Pull request by MarijnS95**
Initial version of the contributing guide. Needs a lot of work, feel free to mention ideas in a review, or commit them to the branch directly. Check for spelling errors, overall correctness and excessive use of my opinion 😉

### CODE REVIEW

**Comment by Jannify** [comment]
What about a Visual Studio settings file to download?

**Comment by MarijnS95** [comment]
@Jannify Yes, I've added such a file to this PR.

Besides regular formatting settings, there's an entire section for so called "language conventions". These are only checked in VS2017 though. I've added everything that's applicable to C# 6.0 and lower.
A lot of what I've written down [here](https://github.com/SubnauticaNitrox/Nitrox/issues/36) (which is based on https://github.com/SubnauticaNitrox/Nitrox/pull/11) is covered by these settings, though we still have to decide which setting we prefer.

@Sunrunner37 I hope you can give an opinion on the settings. Here's a quick list:

- Use of aliases vs CTS: prever `int` and `string` over
- Usage of `var`  - after a quick code search: I'm the only one using this.
- Use blocks for collection initializers: `new List<Foo> { a, b };` vs `.Add(a);` and `.Add(b);` on the next lines.
- Use blocks for object initializers: `new Foo() { Bar = 1 };`.
- Unnecessary use of `this.`.
- Null checking/coalescing operators `?.` and `??`.

And for each of these, we have to determine a severity, one of `none`, `suggestion`, `warning` or `error`. Error does not yet fail the build in VS2017, but eventually that'll be implemented.

I haven't done anything on the [naming convention](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#naming-conventions) settings yet, maybe I'll add some of the default rules there.

Finally, I want to apply this style to all files before merging this PR. There are some tools to do most of it. I/we should, we can't enforce rules when most of the code doesn't adhere to it in the first place.

**Comment by Sunrunner37** [comment]
> Use of aliases vs CTS: prefer int and string over Int32 and String for example.
I think aliases are used most places (except maybe string) - suggestion is probably fine.
 
> Usage of var - after a quick code search: I'm the only one using this.
This is one thing that I'm not favorable on - I don't think saving horizontal space is worth the readability trade off.  - error

> Use blocks for collection initializers: new List<Foo> { a, b }; vs .Add(a); and .Add(b); on the next lines.
Makes sense to me.

> Use blocks for object initializers: new Foo() { Bar = 1 };
eww - c# and it's attributes.... let's not do this please.

> Unnecessary use of this..
Sure, we can nuke these.

Null checking/coalescing operators ?. and ??.
Meh, less readable I believe.

**Comment by MarijnS95** [comment]
> Overall the guidelines look good. Inside of the validation area do we want to call out gameObject.RequireComponent and GuidHelper.RequireObjectFrom?

I'll add that to the guide.

> This is one thing that I'm not favorable on - I don't think saving horizontal space is worth the readability trade off. - error

I think I can agree with that, imho it just makes writing easier to not have to specify the type, especially when working with (nested) generics. If I change this setting, AFAIK VS gives me the option to convert it for me 😀.

> eww - c# and it's attributes.... let's not do this please.

This is not attributes, it's used to set fields and properties after the constructor is called. Basically it changes code like:
```csharp
SomeCrazyObject foo = new SomeCrazyObject();
foo.Bar = "cake";
foo.baz = 1337;
foo.something = anotherThingIDeclaredAbove;
```
into
```csharp
SomeCrazyObject foo = new SomeCrazyObject()
{
    Bar = "cake",
    baz = 1337,
    something = anotherThingIDeclaredAbove
};
```
Which is IMHO much more readable, especially given the indentation. It explicits the fact that these fields/properties are set directly after the constructor, *preventing other lines of code from ending up inbetween*.

> Meh, less readable I believe.

Yup. On the one hand it reduces a lot of ugly `if (foo != null) { foo.Bar(); }` or `foo != null ? foo : bar;`, but on the other hand it makes it more explicit. I think `?.` is too easy to miss, but `foo ?? bar` is fine (they can be configured separately anyway).

**Comment by Sunrunner37** [comment]
Now that it's morning here I'll follow up on these.

>This is not attributes, it's used to set fields and properties after the constructor is called. Basically it changes code like:
You'll have to sometimes read between the lines when I talk as I [come from java](https://stackoverflow.com/questions/8479038/what-is-an-attribute-in-java).  My (subjective) observation is that c# seems to encourage inappropriate intimacy with these types of features.  If you want to create anemic object types (without using the constructor) why not use builder pattern to gain immutability?  

>?. is too easy to miss
That's my opinion as well. (error level maybe?)

>foo ?? bar is fine 
Yup, makes sense to me.  (suggestion level maybe?)

**Comment by MarijnS95** [comment]
> You'll have to sometimes read between the lines when I talk as I come from java. My (subjective) observation is that c# seems to encourage inappropriate intimacy with these types of features. If you want to create anemic object types (without using the constructor) why not use builder pattern to gain immutability?

You are completely right, my apologies. I work in many different languages myself, but only have little experience with Java. When talking about attributes in C#, I think about the `[BlaAttribute]` thingies; it makes no sense for me to think that in this context.

I think you are right though; even if I like the notation over regular `foo.Bar = baz;`, why are we even doing that in the first place? We're not using the builder pattern to begin with, so IMHO the values should be assigned through the constructor.

**Pull request merged**
