### PR TITLE
Patch platform steam to use steam exe to launch game

### PR DESCRIPTION
**Pull request by joshuatam**
Revised to use steam exe to launch game, related to #1723

### CODE REVIEW

**Comment by Jannify** [comment]
After 1.5.0.1 We switched from the "steam launch command" to the game exe so we have full control of the subnautica process. Therefor we are currently discussing options and their pros and cons internally with the author of this part of code.

**Comment by Jannify** [comment]
We discussed this internally and would like to stick with the current solution for now. But we will investigate a solution where you can choose the start method, so you can switch between direct start (current) and steam-link. For now there is a workaround which should work:

- Add `-nitrox <path to Nitrox launcher folder>` to the games launch options in steam
- Launch the game with the launcher and close it once the menu showed up
- Now start the game with steam, it should load Subnautica with Nitrox loaded.

**Comment by kgleken** [comment]
> We discussed this internally and would like to stick with the current solution for now. But we will investigate a solution where you can choose the start method, so you can switch between direct start (current) and steam-link. For now there is a workaround which should work:
> 
> * Add `-nitrox <path to Nitrox launcher folder>` to the games launch options in steam
> * Launch the game with the launcher and close it once the menu showed up
> * Now start the game with steam, it should load Subnautica with Nitrox loaded.

I have 1.6.0.0 and I want to use this workaround so I can play with a controller. I can't tell if I'm doing something wrong.
> * When I launch the game using the nitrox launcher first, do I need to start the server and connect to the multiplayer session before exiting?
> * Is there a certain way that I need to exit in order to relaunch the game and have it work? I can see the server log says "Server has paused. Waiting for players to connect. World state saved."
> * I tried using the -nitrox launch argument. Can you show me how to format it so that I know if I am doing it right? For example I tried -nitrox "C:/Users/Glek/Downloads/Nitrox_1.6.0.0", with and without parenthesis, with both types of slashes and it still isn't working. The game still just launches in single player mode for me.

**Comment by Jannify** [comment]
You don't need to connect to a server in your first launch. Important is that you enter the main menu when you start the game with the Nitrox launcher the first time. Then close the game with the main menu quit button. Then start it with steam, I use backslashes and no parenthesis. The Nitrox Launcher needs to be open the whole time.

**Comment by kgleken** [comment]
Thank you so much for the fast response. I tried what you said, and it worked this time. For some reason I had it in my head that you needed to exit the game not through main menu.

Some other interesting stuff I found out that might be useful to you or others:
* Ultimately my end goal was to get it working on 1.6.0.0 so I could play with VR using a controller. The problem I was having was that the controller actually worked, it just doesn't work on the multiplayer button on the main menu once the game is launched, so you can't join a game. The d-pad kinda works but not on any of the stuff that is added by the Nitrox mod.
* Although the trick above worked to allow me to relaunch the game from steam with multiplayer mode on, it did not fix my problem. Perhaps the controller issue I had was different than [#1723](url) 
* What I was able to do however was use the d-pad/look around using my oculus to select menu options. To join a server I could click using my mouse, then on the next screen I was able to join by pressing the "Enter" key on my keyboard. Once I was in the game I could use my controller like normal
* I'm guessing that anybody can repeat these steps as a workaround as long as they are the one hosting server (the options for 127.0.0.1 are already pre-filled). Not sure if it still works to join another person's server, but my friends aren't using vr anyway, so I can just be the one to host

**Pull request closed without merging**
