### PR TITLE
Scrolling chat log

### PR DESCRIPTION
**Pull request by ASimpson87**
Scrolling chat log , mouse activated on chat entry mouse wheel to scroll chat up and down. Asset bundle  chatlog will need to be shipped with installer.

### CODE REVIEW

**Comment by ASimpson87** [comment]
Yes we do...

**Comment by Measurity** [comment]
When this is merged we should probably have a tut on how to maintain the assetbundle.

- Install Unity 5.6
- Add assetbundle to a Unity project
- Open it

I assume we might also need the .meta files that Unity exports alongside assets. Maybe it's a good idea to create a new repo for the Unity assets as a Unity 5.6 project @Sunrunner37

**Comment by Sunrunner37** [comment]
Ok I can create the project and can include this stuff in the installer.  Should Simpson configure unity to export metadata for the asset (so it can be included in this PR) before I merge?  Also, can you take a crack at creating that documentation Simpson?

**Comment by ASimpson87** [comment]
Ok i have the meta files so i can add them to the new repo when its up. I'll do the readme for the asset bundles.

**Pull request merged**
