### PR TITLE
Cyclops Syncing

### PR DESCRIPTION
**Pull request by RabidCrab**
Cyclops syncing of:

- Spawn
- Destruction
- Damage Points
- Fires
- Collisions
- Creature Damage
- Depth

### CODE REVIEW

**Comment by RabidCrab** [comment]
Forgot to remove commented out code and rebase the commit.

**Comment by MarijnS95** [comment]
You **shouldn't** close the PR for that - you can make the changes and push them to the same branch, the PR automatically follows along.

**Comment by RabidCrab** [comment]
Apologies, didn't notice you reopened the pull request. Visual Studio's team explorer set the origin master to the upstream master, or I did that myself by accident. I intended to pull onto my master, then do a pull request from there.

**Comment by MarijnS95** [comment]
Ah I see. Personally prefer to PR from my feature branch, especially useful when working on multiple features at the same time. Then I keep master up to date with the main repo.

**Pull request closed without merging**
