### PR TITLE
[WIP] Add status codes to nitrox server console

### PR DESCRIPTION
**Pull request by OhmV-IR**
Ideally, status codes should be able to be googled in the docs to allow people to troubleshoot themselves without looking at the code or asking in the discord. Realistically, most people will still ask in the discord :{. This is a WORK IN PROGRESS, and the pull request will be marked as ready to be reviewed when it is ready. If you would like to contact me about this PR, add me on discord "ohmvir" <- no quotation marks. My DMs are closed so you will have to wait for me to accept your friend request
Example of how it would look like:
`The server failed to start`
`Status code = 5`
On website: Status code 5 is caused due to Nitrox not having sufficient permissions to access a file. Please ensure that Nitrox is run as an administrator and try again

### CODE REVIEW

**Comment by tornac1234** [comment]
If we were to implement this kind of thing, we'd likely have a static function somewhere returning the concatenation of the const string "Status code " (variable somewhere) and the filled number.

**Comment by OhmV-IR** [comment]
@tornac1234 Yes of course, was just testing stuff for how you print to console and made a commit so that I could open this PR

**Comment by dartasen** [comment]
Make sure to create a proper branch on your Nitrox fork, it's not recommended to commit on the master branch directly

**Comment by OhmV-IR** [comment]
@killzoms I've updated my inDev branch on the forked repo with your suggestion

**Comment by killzoms** [comment]
Enum does have a ToString overload that takes a format, said format can cause either a base 10 number, Hexadecimal, or a strung

**Comment by killzoms** [comment]
Miss click my apologies.

**Comment by killzoms** [comment]
Anyways, as i was about to say, [These](https://learn.microsoft.com/en-us/dotnet/standard/base-types/enumeration-format-strings) are the formats supported by the Enum type

**Comment by OhmV-IR** [comment]
reopening PR with merge from polishing-status-codes, not master

**Pull request closed without merging**
