### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FuseBarTV**

### CODE REVIEW

**Comment by dartasen** [comment]
Are you ok ?

**Comment by FuseBarTV** [comment]
my brain ded

**Comment by Sneethan** [comment]
LMAO rip bozo

**Comment by dartasen** [comment]
@FuseBarTV I recommand you to delete https://github.com/FuseBarTV/NitroxPatched which is an illegal fork that do not respect the LICENSE Nitrox is under 😃

**Comment by FuseBarTV** [comment]
May I ask why it's illegal? I'm not directly condoning the use of piracy.

**Comment by dartasen** [comment]
@FuseBarTV > May I ask why it's illegal? I'm not directly condoning the use of piracy.

- The main point is that you're encouraging piracy. You can't provide a crack-friendly version and state aftewards "I swear I do not encourage anything, please buy the real game". First, this is against what we want. Second, UWE (Subnautica's dev) allowed us to do this mod by not allowing cracked version, they won't be glad if we text them about it.

- Concerning the license, you must
   1. State all significant changes made to the original software
   2. Make available the original source code when you distribute any binaries based on the licensed work
   3. Include a copy of the original copyright notice
   4. ...

I did not check every file to find what you modified exactly, which proves that you must have break the first statement.
Then, you did not use the fork system and you remove the link from the README, which drops link to the original source. You uploaded the whole repository as it was yours, which drops the history and the link to the authors of commits. which breaks the second point.
Besides, you significantly changed the README which include links, statements from our team (we -> I, seriously ?), ... Which breaks the third point.

Open-Source License doesn't mean you can do whatever you want with products that you don't own.

**Comment by FuseBarTV** [comment]
Firstly, I did link to your website.
Secondly, the change from We to I is specifically changed to text I have added to the README.
Thirdly, as much as game devs don't link software piracy, it's everywhere and people need to accept that piracy is not going away or changing. I personally use legit Subnautica now but that doesn't mean everyone will.

**Comment by FuseBarTV** [comment]
I'm not completely doing this for myself, I am going to use it volume use with multiple computers, but also for the community who just want to play the game without having DRM issues. I've had problems with Steam's DRM before and Nitrox not starting hence why I've patched the game in a way that unlocks it.

> Our website is not the product we're offering, thus this is out of context.

The website is what you are offering? Why do you have a website dedicated to Nitrox if it's not even about Nitrox? Sounds odd to me.

> in the process you're spitting on our work and on UWE.

I'm not attempting to "spit" on your work and UWE's. The game itself is great and the multiplayer mod is incredible! The fact that the nitrox team have made a multiplayer mod from scratch is pretty cool I think!
I'm sorry if I came out to be aggressive towards your team or the team at UWE, I'm not attempting to be.

**Comment by dartasen** [comment]
> I'm not completely doing this for myself, I am going to use it volume use with multiple computers, but also for the community who just want to play the game without having DRM issues. I've had problems with Steam's DRM before and Nitrox not starting hence why I've patched the game in a way that unlocks it.

Maybe you've had DRM isssues, but my question is why you did not reach us with github issues or discord ? Maybe you have good attention but this is clearly the wrong way to do it.

> The website is what you are offering? Why do you have a website dedicated to Nitrox if it's not even about Nitrox? Sounds odd to me.

The website is a platform to access the final product (executable), it is not the product itself. Which is way different and do not cover the license purpose.

**Comment by FuseBarTV** [comment]
The main thing here is, you can't stop software piracy regardless of what I'm using it for, if people were to use it for illegitimate purposes, you can't stop people from doing it, you can attempt to suspend GitHub repositories but in no way will you be able to stop software piracy in this sense. I will make it clear that I have paid for the game but there are other demographics that can't afford the game or they would like to try it before they buy it (which is what I normally do with PC games). Thanks.

**Pull request closed without merging**
