### PR TITLE
PDA,Power,Item Fix

### PR DESCRIPTION
**Pull request by garsia0**
Remove Notification Goal Event On Item You Already have On Inventory
Sync And Save (KnownTech Entries,PDAScanner Entries,PDAEncyclopediaEntries )
All Progress of Encyclopedia and BluePrint Fixed
Add Comand (mpsave) to force save game on server
Add Notifiacion Sync of Partial Scan Of Item
PowerLevelChangedProcessor Bug Drain Loop Fix

### CODE REVIEW

**Comment by garsia0** [comment]
Clean PR for better history

**Comment by MarijnS95** [comment]
@garsia0 You did not have to close and redo the pull request for this. We actually **wan** to have that history to be able to track whether review requests have been adressed.

I recommend closing this PR and reopening the other one; it'll still track the same branch.

**Comment by garsia0** [comment]
i try to make a rebase and fuck entire repository xD

**Comment by garsia0** [comment]
Issues Need Close
https://github.com/SubnauticaNitrox/Nitrox/issues/210 < Close
https://github.com/SubnauticaNitrox/Nitrox/issues/196 < Close
https://github.com/SubnauticaNitrox/Nitrox/issues/169  < Close
https://github.com/SubnauticaNitrox/Nitrox/issues/133 > Done
https://github.com/SubnauticaNitrox/Nitrox/issues/123 > Done

**Comment by MarijnS95** [comment]
You do not need to make separate forks, that's what branches are for. I recommend you to familiarize with that topic, and know you can always ask for help here on github or in discord :)

**Pull request merged**
