### PR TITLE
Improve vehicle destruction sync

### PR DESCRIPTION
**Pull request by SpaceMonkeyy86**
Properly moves vehicle destroying to the new entities system.

### CODE REVIEW

**Comment by SpaceMonkeyy86** [comment]
Cyclops wrecks are also synced now

**Comment by dartasen** [comment]
Works fine IG :

* We can see seamoth & exosuit being destroyed
* We can see cyclops exploding
* Wrecks are still here upon re-joining (with items, upgrades in it)

Bugs we noticed : 
* Wrecks will re-explode upon re-joining
* Decoys slots are gone upon re-joining

**Comment by SpaceMonkeyy86** [comment]
> Works fine IG :
> 
>     * We can see seamoth & exosuit being destroyed
> 
>     * We can see cyclops exploding
> 
>     * Wrecks are still here upon re-joining (with items, upgrades in it)
> 
> 
> Bugs we noticed :
> 
>     * Wrecks will re-explode upon re-joining
> 
>     * Decoys slots are gone upon re-joining

Both of these should be fixed now.

**Review by Jannify — CHANGES_REQUESTED** [review]

**Review by Jannify — APPROVED** [review]
In `SubRoot_SetCyclopsUpgrades_Patch.cs#L18` you have the return in the same line. Nitrox code style normally says that we do brackets for every if.

Besides that LGTM CW

**Review by tornac1234 — APPROVED** [review]
clear enough CW

**Pull request merged**
